/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZukanRouteImport } from './routes/zukan'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as Phase1bStorageTestRouteImport } from './routes/phase1b-storage-test'
import { Route as Phase0ImmersionTestRouteImport } from './routes/phase0-immersion-test'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const ZukanRoute = ZukanRouteImport.update({
  id: '/zukan',
  path: '/zukan',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase1bStorageTestRoute = Phase1bStorageTestRouteImport.update({
  id: '/phase1b-storage-test',
  path: '/phase1b-storage-test',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase0ImmersionTestRoute = Phase0ImmersionTestRouteImport.update({
  id: '/phase0-immersion-test',
  path: '/phase0-immersion-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/phase0-immersion-test': typeof Phase0ImmersionTestRoute
  '/phase1b-storage-test': typeof Phase1bStorageTestRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zukan': typeof ZukanRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/phase0-immersion-test': typeof Phase0ImmersionTestRoute
  '/phase1b-storage-test': typeof Phase1bStorageTestRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zukan': typeof ZukanRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/phase0-immersion-test': typeof Phase0ImmersionTestRoute
  '/phase1b-storage-test': typeof Phase1bStorageTestRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zukan': typeof ZukanRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/phase0-immersion-test'
    | '/phase1b-storage-test'
    | '/scan'
    | '/settings'
    | '/sitemap.xml'
    | '/zukan'
    | '/checkout/return'
    | '/api/public/version'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/phase0-immersion-test'
    | '/phase1b-storage-test'
    | '/scan'
    | '/settings'
    | '/sitemap.xml'
    | '/zukan'
    | '/checkout/return'
    | '/api/public/version'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/phase0-immersion-test'
    | '/phase1b-storage-test'
    | '/scan'
    | '/settings'
    | '/sitemap.xml'
    | '/zukan'
    | '/checkout/return'
    | '/api/public/version'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Phase0ImmersionTestRoute: typeof Phase0ImmersionTestRoute
  Phase1bStorageTestRoute: typeof Phase1bStorageTestRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZukanRoute: typeof ZukanRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zukan': {
      id: '/zukan'
      path: '/zukan'
      fullPath: '/zukan'
      preLoaderRoute: typeof ZukanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase1b-storage-test': {
      id: '/phase1b-storage-test'
      path: '/phase1b-storage-test'
      fullPath: '/phase1b-storage-test'
      preLoaderRoute: typeof Phase1bStorageTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase0-immersion-test': {
      id: '/phase0-immersion-test'
      path: '/phase0-immersion-test'
      fullPath: '/phase0-immersion-test'
      preLoaderRoute: typeof Phase0ImmersionTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Phase0ImmersionTestRoute: Phase0ImmersionTestRoute,
  Phase1bStorageTestRoute: Phase1bStorageTestRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZukanRoute: ZukanRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
